# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'

steps:
- task: UseDotNet@2
  displayName: 'Set .NET version'
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true

- task: CmdLine@2
  displayName: Install MAUI
  inputs:
    script: |
      dotnet workload install maui

- task: DotNetCoreCLI@2
  displayName: 'Build API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Notl.MuseumMap.Api.csproj'
    zipAfterPublish: true
    modifyOutputPath: true
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/api'
    
- task: DotNetCoreCLI@2
  displayName: 'Build Web'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Notl.MuseumMap.Web.csproj'
    zipAfterPublish: true
    modifyOutputPath: true
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/web'

- task: DotNetCoreCLI@2
  displayName: 'Build Admin'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Notl.MuseumMap.Admin.csproj'
    zipAfterPublish: true
    modifyOutputPath: true
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/admin'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'