//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notl.MuseumMap.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notl.MuseumMap.App.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events were found nearby.  Try again or use the event code to join in..
        /// </summary>
        public static string Alert_EventsNotFound_Message {
            get {
                return ResourceManager.GetString("Alert_EventsNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events found.
        /// </summary>
        public static string Alert_EventsNotFound_Title {
            get {
                return ResourceManager.GetString("Alert_EventsNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we can&apos;t determine your current location.  You can retry or search for your event by name..
        /// </summary>
        public static string Alert_LocationNotFound_Message {
            get {
                return ResourceManager.GetString("Alert_LocationNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location not found.
        /// </summary>
        public static string Alert_LocationNotFound_Title {
            get {
                return ResourceManager.GetString("Alert_LocationNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request it team can be contacted at support@requestit.ca for support issues or sales@requestit.ca for general sales inqueries..
        /// </summary>
        public static string App_ContactInfo {
            get {
                return ResourceManager.GetString("App_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request It.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # TERMS AND CONDITIONS OF
        ///# REQUEST IT APP
        ///
        ///## Last revision: Jan 9, 2023
        ///
        ///PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS WEBSITE.
        ///
        ///The following Terms and Conditions govern and apply to your use of or reliance upon this website maintained by 2721683 Ontario Incorporated (the &quot;Website&quot;).
        ///Your access or use of the Website indicates that you have read, understand and agree to be bound by these Terms and Conditions and any other applicable laws, statutes and/or regulations. We may change th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string App_TermsOfUse_Markdown {
            get {
                return ResourceManager.GetString("App_TermsOfUse_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start event.
        /// </summary>
        public static string Button_AddEvent {
            get {
                return ResourceManager.GetString("Button_AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        public static string Button_ApplyChanges {
            get {
                return ResourceManager.GetString("Button_ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear settings.
        /// </summary>
        public static string Button_ClearSettings {
            get {
                return ResourceManager.GetString("Button_ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start event.
        /// </summary>
        public static string Button_CreateEvent {
            get {
                return ResourceManager.GetString("Button_CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an event.
        /// </summary>
        public static string Button_FindEvent {
            get {
                return ResourceManager.GetString("Button_FindEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Button_JoinEvent {
            get {
                return ResourceManager.GetString("Button_JoinEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Button_JoinNow {
            get {
                return ResourceManager.GetString("Button_JoinNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a request.
        /// </summary>
        public static string Button_MakeRequest {
            get {
                return ResourceManager.GetString("Button_MakeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Button_OpenMyEvent {
            get {
                return ResourceManager.GetString("Button_OpenMyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use code.
        /// </summary>
        public static string Button_SearchByCode {
            get {
                return ResourceManager.GetString("Button_SearchByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find events nearby.
        /// </summary>
        public static string Button_SearchByLocation {
            get {
                return ResourceManager.GetString("Button_SearchByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request it.
        /// </summary>
        public static string Button_SelectSong {
            get {
                return ResourceManager.GetString("Button_SelectSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start an event.
        /// </summary>
        public static string Button_StartEvent {
            get {
                return ResourceManager.GetString("Button_StartEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request it.
        /// </summary>
        public static string Button_SubmitRequest {
            get {
                return ResourceManager.GetString("Button_SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed information.
        /// </summary>
        public static string Label_AlertDetails {
            get {
                return ResourceManager.GetString("Label_AlertDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Insights Key.
        /// </summary>
        public static string Label_AppInsightsKey {
            get {
                return ResourceManager.GetString("Label_AppInsightsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Attendees, {1} Requests.
        /// </summary>
        public static string Label_AttendeeAndRequestCount {
            get {
                return ResourceManager.GetString("Label_AttendeeAndRequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Attendees.
        /// </summary>
        public static string Label_AttendeeCount {
            get {
                return ResourceManager.GetString("Label_AttendeeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string Label_AttendeeEmail {
            get {
                return ResourceManager.GetString("Label_AttendeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string Label_AttendeeName {
            get {
                return ResourceManager.GetString("Label_AttendeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend API.
        /// </summary>
        public static string Label_BaseUrl {
            get {
                return ResourceManager.GetString("Label_BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build number.
        /// </summary>
        public static string Label_BuildNumber {
            get {
                return ResourceManager.GetString("Label_BuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2372977 Ontario Inc. (Canada).
        /// </summary>
        public static string Label_CompanyName {
            get {
                return ResourceManager.GetString("Label_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string Label_ContactInfo {
            get {
                return ResourceManager.GetString("Label_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event code.
        /// </summary>
        public static string Label_EventCode {
            get {
                return ResourceManager.GetString("Label_EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Label_EventLocation {
            get {
                return ResourceManager.GetString("Label_EventLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string Label_EventName {
            get {
                return ResourceManager.GetString("Label_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form validation errors.
        /// </summary>
        public static string Label_FormErrors {
            get {
                return ResourceManager.GetString("Label_FormErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request It App (Attendee).
        /// </summary>
        public static string Label_FullAppName {
            get {
                return ResourceManager.GetString("Label_FullAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to make a song request!.
        /// </summary>
        public static string Label_MakeFirstRequest {
            get {
                return ResourceManager.GetString("Label_MakeFirstRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for music songs and artists.
        /// </summary>
        public static string Label_MusicKeyword {
            get {
                return ResourceManager.GetString("Label_MusicKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no results found..
        /// </summary>
        public static string Label_MusicNotFound {
            get {
                return ResourceManager.GetString("Label_MusicNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, you have no active DJ events..
        /// </summary>
        public static string Label_NoDjEventsFound {
            get {
                return ResourceManager.GetString("Label_NoDjEventsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new requests yet.
        /// </summary>
        public static string Label_NoRequestsYet {
            get {
                return ResourceManager.GetString("Label_NoRequestsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by: {0}.
        /// </summary>
        public static string Label_RequestedByFormat {
            get {
                return ResourceManager.GetString("Label_RequestedByFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string Label_TermsOfUse {
            get {
                return ResourceManager.GetString("Label_TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version information.
        /// </summary>
        public static string Label_VersionInfo {
            get {
                return ResourceManager.GetString("Label_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version number.
        /// </summary>
        public static string Label_VersionNumber {
            get {
                return ResourceManager.GetString("Label_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an event.
        /// </summary>
        public static string Menu_FindEvent {
            get {
                return ResourceManager.GetString("Menu_FindEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start an event.
        /// </summary>
        public static string Menu_StartEvent {
            get {
                return ResourceManager.GetString("Menu_StartEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an event.
        /// </summary>
        public static string Pages_Attendees_EventFinderPage_Title {
            get {
                return ResourceManager.GetString("Pages_Attendees_EventFinderPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event requests.
        /// </summary>
        public static string Pages_Attendees_EventPage_Title {
            get {
                return ResourceManager.GetString("Pages_Attendees_EventPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join your event.
        /// </summary>
        public static string Pages_Attendees_JoinDialog_Title {
            get {
                return ResourceManager.GetString("Pages_Attendees_JoinDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for music.
        /// </summary>
        public static string Pages_Attendees_MusicSearchPage_Title {
            get {
                return ResourceManager.GetString("Pages_Attendees_MusicSearchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request song.
        /// </summary>
        public static string Pages_Attendees_RequestDialog_Title {
            get {
                return ResourceManager.GetString("Pages_Attendees_RequestDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Request It.
        /// </summary>
        public static string Pages_Common_AboutPage_Title {
            get {
                return ResourceManager.GetString("Pages_Common_AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Pages_Common_ErrorDialog_Error_Title {
            get {
                return ResourceManager.GetString("Pages_Common_ErrorDialog_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Pages_Common_ErrorDialog_Information_Title {
            get {
                return ResourceManager.GetString("Pages_Common_ErrorDialog_Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Pages_Common_ErrorDialog_Warning_Title {
            get {
                return ResourceManager.GetString("Pages_Common_ErrorDialog_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string Pages_Common_SettingsPage_Title {
            get {
                return ResourceManager.GetString("Pages_Common_SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event console.
        /// </summary>
        public static string Pages_Dj_ConsolePage_Title {
            get {
                return ResourceManager.GetString("Pages_Dj_ConsolePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My DJ events.
        /// </summary>
        public static string Pages_Djs_MyEventPage_Title {
            get {
                return ResourceManager.GetString("Pages_Djs_MyEventPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new event.
        /// </summary>
        public static string Pages_Djs_StartEventDialog_Title {
            get {
                return ResourceManager.GetString("Pages_Djs_StartEventDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Tip_Back {
            get {
                return ResourceManager.GetString("Tip_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to dark mode.
        /// </summary>
        public static string Tip_DarkMode {
            get {
                return ResourceManager.GetString("Tip_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to light mode.
        /// </summary>
        public static string Tip_LightMode {
            get {
                return ResourceManager.GetString("Tip_LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the menu.
        /// </summary>
        public static string Tip_Menu {
            get {
                return ResourceManager.GetString("Tip_Menu", resourceCulture);
            }
        }
    }
}
